[test]
coverage = true
coverageReporter = ["text"]
coverageSkipTestFiles = true
coverageThreshold = { functions = 1.0, lines = 1.0 }
coveragePathIgnorePatterns = [
  "**/__tests__/**",
  "**/main.ts",
  "**/composition.ts",
]
