ls:
  .dir: kebab-case | regex:^__tests__$ | regex:^\.[a-z0-9]+(-[a-z0-9]+)*$
  .*: kebab-case | regex:^\.[a-z0-9]+(-[a-z0-9]+)*$
  .md: kebab-case | regex:^[A-Z]+(_[A-Z]+)*$
ignore:
  - .git
  - .devkit
  - .stryker-tmp
  - node_modules
  - coverage
  - dist
  - reports
