name: 🚀 Deploy

on:
  release:
    types: [released]

jobs:
  deploy:
    uses: droneey/.github/.github/workflows/cd-deploy-npm.yml@v1
    permissions:
      contents: read
      id-token: write
    with:
      packages: "packages/typescript/libs/*/package.json"
      node-version: "24"
    secrets:
      npm_token: ${{ secrets.NPM_TOKEN }}
