name: 🔖 Pre-release

on:
  push:
    tags: ['v*']

jobs:
  pre-release:
    uses: droneey/.github/.github/workflows/cd-release.yml@v2.5.0
    permissions:
      contents: write
    with:
      prerelease: true
      assets-command: tar --exclude='__tests__' -czf devkit.tar.gz -C packages common && sha256sum devkit.tar.gz > devkit.tar.gz.sha256
      assets: devkit.tar.gz devkit.tar.gz.sha256
