name: 🏷️ Version

on:
  push:
    branches: [main]

concurrency:
  group: version
  cancel-in-progress: false

jobs:
  version:
    if: "!startsWith(github.event.head_commit.message, 'chore: Release v')"
    uses: droneey/workflows/.github/workflows/cd-version.yml@v1
    permissions:
      contents: write
      pull-requests: read
    with:
      packages: "package.json packages/typescript/libs/*/package.json"
    secrets:
      token: ${{ secrets.GH_ORG_TOKEN }}
